"""
Closed-Loop Drone Simulation Engine
Executes complete mission with closed-loop flight on EKF estimate,
sensor noise, cyberattack injection, anomaly detection, resilience gating,
and telemetry logging.
Supports both defense ON (D2) and defense OFF (D1 baseline contrast).
"""

import os
import json
import yaml
import numpy as np
import pandas as pd
from typing import Dict, Any, List, Optional

from cyber_drone.ekf import DroneEKF
from cyber_drone.sensor_sim import SensorSimulator
from cyber_drone.attack_injector import AttackInjector
from cyber_drone.anomaly_detector import AnomalyDetector
from cyber_drone.resilience_manager import ResilienceManager
from cyber_drone.astar_planner import AStarPlanner
from cyber_drone.metrics import MetricsEvaluator


class SimulationEngine:
    def __init__(
        self,
        scenario_config: Dict[str, Any],
        sensors_config: Dict[str, Any],
        estimator_config: Dict[str, Any],
        detector_config: Dict[str, Any],
        resilience_config: Dict[str, Any],
        planner_config: Dict[str, Any],
        defense_on: bool = True,
        seed: int = 42
    ):
        self.scenario_cfg = scenario_config
        self.defense_on = defense_on
        self.seed = seed

        # Subsystems
        self.sensor_sim = SensorSimulator(sensors_config, seed=seed)
        self.attack_injector = AttackInjector(scenario_config, seed=seed)
        self.main_ekf = DroneEKF(is_trusted=False, config=estimator_config)
        self.trusted_ekf = DroneEKF(is_trusted=True, config=estimator_config)
        self.detector = AnomalyDetector(detector_config)
        self.resilience_mgr = ResilienceManager(resilience_config)
        self.planner = AStarPlanner(planner_config)

        # Mission parameters
        mission = scenario_config.get("mission", {})
        self.start_point = np.array(mission.get("start_point", [0.0, 0.0, 10.0]))
        self.goal_point = np.array(mission.get("goal_point", [60.0, 40.0, 10.0]))
        # Initial collision-free path generated by A* planner
        init_plan = self.planner.plan(
            start_world=(self.start_point[0], self.start_point[1]),
            goal_world=(self.goal_point[0], self.goal_point[1]),
            under_attack=False
        )
        if not init_plan["emergency"] and len(init_plan["waypoints"]) >= 2:
            self.nominal_waypoints = init_plan["waypoints"]
        else:
            self.nominal_waypoints = [list(wp) for wp in mission.get("waypoints", [
                [15.0, 8.0, 10.0],
                [30.0, 18.0, 10.0],
                [45.0, 30.0, 10.0],
                [60.0, 40.0, 10.0]
            ])]
        self.current_waypoints = [wp.copy() for wp in self.nominal_waypoints]
        self.current_wp_idx = 0

        # Kinematic drone true state: pos [x, y, z], vel [vx, vy, vz], yaw
        self.truth_pos = self.start_point.copy()
        self.truth_vel = np.zeros(3)
        self.truth_yaw = 0.0

        # Filters initialization
        self.main_ekf.reset(self.truth_pos, self.truth_yaw)
        self.trusted_ekf.reset(self.truth_pos, self.truth_yaw)

        # Simulation clock
        self.dt = 0.02 # 50 Hz control loop
        self.total_duration = float(scenario_config.get("mission_duration_sec", 75.0))
        self.current_time = 0.0

        # Telemetry logs
        self.telemetry_records: List[Dict[str, Any]] = []
        self.trust_records: List[Dict[str, Any]] = []

    def run(self) -> Dict[str, Any]:
        """
        Runs the simulation to completion.
        """
        steps = int(self.total_duration / self.dt)

        for step in range(steps):
            self.current_time = round(step * self.dt, 4)
            self._step_simulation(step)

        # Compile telemetry dataframe
        df_telemetry = pd.DataFrame(self.telemetry_records)
        df_trust = pd.DataFrame(self.trust_records)

        # Evaluate performance metrics
        metrics = MetricsEvaluator.evaluate(
            telemetry_df=df_telemetry,
            events=self.resilience_mgr.events,
            scenario_cfg=self.scenario_cfg,
            defense_on=self.defense_on,
            obstacles=self.planner.obstacles
        )

        return {
            "telemetry": df_telemetry,
            "trust": df_trust,
            "events": self.resilience_mgr.events,
            "quarantine": self.resilience_mgr.quarantine_log,
            "metrics": metrics,
            "config": {
                "scenario": self.scenario_cfg,
                "defense_on": self.defense_on,
                "seed": self.seed
            }
        }

    def _step_simulation(self, step: int):
        t = self.current_time

        # 1. Generate Raw Sensors from True Kinematics
        raw_gps_pos, raw_gps_vel = self.sensor_sim.generate_gps(self.truth_pos, self.truth_vel)
        raw_accel, raw_gyro = self.sensor_sim.generate_imu(np.zeros(3), self.truth_yaw, 0.0)
        raw_baro_alt = self.sensor_sim.generate_baro(self.truth_pos[2])
        raw_vis_pos, raw_vis_vel, raw_vis_yaw = self.sensor_sim.generate_vision(t, self.truth_pos, self.truth_yaw, self.truth_vel)
        raw_lidar_ranges, raw_lidar_alt = self.sensor_sim.generate_lidar(self.truth_pos[2], self.planner.obstacles, self.truth_pos)

        # 2. Attack Injection Layer
        attack_gps = self.attack_injector.process_gps(t, raw_gps_pos, raw_gps_vel)
        attack_accel, attack_gyro = self.attack_injector.process_imu(t, raw_accel, raw_gyro)
        attack_lidar_ranges, attack_lidar_alt = self.attack_injector.process_lidar(t, raw_lidar_ranges, raw_lidar_alt)

        # Record sensor timestamps for watchdog check
        if attack_gps is not None:
            self.detector.record_sensor_message("gps", t)
        self.detector.record_sensor_message("imu", t)
        self.detector.record_sensor_message("baro", t)
        self.detector.record_sensor_message("vision", t)
        self.detector.record_sensor_message("lidar", t)

        # 3. Predict Step for Both Filters (using IMU)
        self.main_ekf.predict(self.dt, attack_accel, attack_gyro[2])
        self.trusted_ekf.predict(self.dt, attack_accel, attack_gyro[2])

        # 4. Measurement Update Step
        main_gps_diag = None
        if attack_gps is not None:
            # If defense is ON and GPS is isolated, quarantine it instead of updating main EKF
            if self.defense_on and "gps" in self.resilience_mgr.isolated_sensors:
                self.resilience_mgr.log_quarantine("gps", t, attack_gps[0].tolist(), "Quarantined by Resilience Manager")
            else:
                main_gps_diag = self.main_ekf.update_gps(attack_gps[0], attack_gps[1])

        self.main_ekf.update_baro(raw_baro_alt)
        self.main_ekf.update_vision(raw_vis_pos, raw_vis_yaw)
        self.main_ekf.update_lidar_altitude(attack_lidar_alt)

        # Trusted filter updates (NEVER GPS)
        self.trusted_ekf.update_baro(raw_baro_alt)
        self.trusted_ekf.update_vision(raw_vis_pos, raw_vis_yaw)
        self.trusted_ekf.update_lidar_altitude(attack_lidar_alt)

        # 5. Anomaly Detection and Resilience Manager (Runs at 10 Hz)
        detection_res = {"status": "NORMAL", "compromised_sensors": [], "risk_score": 0.0, "attack_type": "none"}
        if step % 5 == 0:
            gps_input_pos = attack_gps[0] if attack_gps is not None else None
            nis_val = main_gps_diag["NIS"] if main_gps_diag else None
            
            # Integrated IMU velocity vs vision velocity estimate
            imu_vel = self.main_ekf.velocity
            vis_vel = raw_vis_vel

            detection_res = self.detector.check_all(
                current_time=t,
                gps_pos=gps_input_pos,
                trusted_pos=self.trusted_ekf.position,
                trusted_cov_pos=self.trusted_ekf.position_covariance,
                main_gps_nis=nis_val,
                imu_integrated_vel=imu_vel,
                vision_vel=vis_vel,
                lidar_alt=attack_lidar_alt,
                baro_alt=raw_baro_alt
            )

            # If Defense is ON, Resilience Manager reacts to detections
            if self.defense_on:
                res_outcome = self.resilience_mgr.update(
                    current_time=t,
                    detection_result=detection_res,
                    main_ekf=self.main_ekf,
                    trusted_ekf=self.trusted_ekf
                )

                # Replan if mode changed or attack confirmed
                if res_outcome["replan_required"]:
                    safe_start = (self.trusted_ekf.position[0], self.trusted_ekf.position[1])
                    safe_goal = (self.goal_point[0], self.goal_point[1])
                    plan_res = self.planner.plan(
                        start_world=safe_start,
                        goal_world=safe_goal,
                        under_attack=True,
                        cyber_risk_score=detection_res["risk_score"]
                    )
                    self.current_waypoints = plan_res["waypoints"]
                    self.current_wp_idx = 0
                    self.resilience_mgr.record_event("SAFE_TRAJECTORY_REPLANNED", t, {
                        "waypoints_count": len(self.current_waypoints),
                        "max_vel": plan_res["maximum_velocity"]
                    })

        # 6. Navigation and Flight Control (Flies on the selected estimate)
        # In Defense OFF: Always uses main EKF (even when spoofed!)
        # In Defense ON: Uses active_estimator chosen by Resilience Manager (switches to trusted)
        if self.defense_on:
            active_pos = self.trusted_ekf.position if self.resilience_mgr.active_estimator == "trusted" else self.main_ekf.position
        else:
            active_pos = self.main_ekf.position

        # Determine target waypoint
        if self.current_wp_idx < len(self.current_waypoints):
            target_wp = np.array(self.current_waypoints[self.current_wp_idx])
            dist_to_wp = np.linalg.norm(active_pos[:2] - target_wp[:2])
            if dist_to_wp < 2.0:
                self.current_wp_idx += 1
                if self.current_wp_idx < len(self.current_waypoints):
                    target_wp = np.array(self.current_waypoints[self.current_wp_idx])
        else:
            target_wp = self.goal_point

        # Speed limit: nominal (3.0 m/s) or degraded (1.5 m/s) under attack
        speed_limit = 1.5 if (self.defense_on and self.resilience_mgr.state in ["CONTAINMENT", "SAFE_NAVIGATION"]) else 3.0

        # Velocity setpoint towards target waypoint based on ESTIMATE
        pos_err = target_wp - active_pos
        horiz_dist = np.linalg.norm(pos_err[:2])
        if horiz_dist > 0.1:
            cmd_vel_xy = (pos_err[:2] / horiz_dist) * min(speed_limit, horiz_dist * 0.8)
        else:
            cmd_vel_xy = np.zeros(2)

        cmd_vel_z = np.clip(pos_err[2] * 0.5, -1.0, 1.0)
        cmd_vel = np.array([cmd_vel_xy[0], cmd_vel_xy[1], cmd_vel_z])

        # 7. Drone Kinematic Physics Update
        # Closed-loop: The drone acts on the velocity setpoint with realistic drag and acceleration limits
        accel_limit = 2.5
        vel_err = cmd_vel - self.truth_vel
        accel_cmd = np.clip(vel_err * 2.0, -accel_limit, accel_limit)

        self.truth_vel += accel_cmd * self.dt
        self.truth_pos += self.truth_vel * self.dt

        if np.linalg.norm(self.truth_vel[:2]) > 0.1:
            self.truth_yaw = np.arctan2(self.truth_vel[1], self.truth_vel[0])

        # 8. Record Telemetry
        gps_record_pos = attack_gps[0] if attack_gps is not None else np.array([np.nan, np.nan, np.nan])
        quarantined = (self.defense_on and "gps" in self.resilience_mgr.isolated_sensors and attack_gps is not None)

        self.telemetry_records.append({
            "time": t,
            "truth_x": round(self.truth_pos[0], 3),
            "truth_y": round(self.truth_pos[1], 3),
            "truth_z": round(self.truth_pos[2], 3),
            "main_est_x": round(self.main_ekf.position[0], 3),
            "main_est_y": round(self.main_ekf.position[1], 3),
            "main_est_z": round(self.main_ekf.position[2], 3),
            "trusted_est_x": round(self.trusted_ekf.position[0], 3),
            "trusted_est_y": round(self.trusted_ekf.position[1], 3),
            "trusted_est_z": round(self.trusted_ekf.position[2], 3),
            "active_est_x": round(active_pos[0], 3),
            "active_est_y": round(active_pos[1], 3),
            "active_est_z": round(active_pos[2], 3),
            "gps_x": round(gps_record_pos[0], 3),
            "gps_y": round(gps_record_pos[1], 3),
            "gps_z": round(gps_record_pos[2], 3),
            "gps_quarantined": quarantined,
            "state": self.resilience_mgr.state if self.defense_on else "DEFENSE_OFF",
            "active_estimator": self.resilience_mgr.active_estimator if self.defense_on else "main",
            "risk_score": detection_res.get("risk_score", 0.0),
            "attack_active": self.attack_injector.is_active(t)
        })

        if step % 5 == 0:
            self.trust_records.append({
                "time": t,
                "gps_trust": self.resilience_mgr.sensor_trust["gps"] if self.defense_on else 1.0,
                "imu_trust": self.resilience_mgr.sensor_trust["imu"] if self.defense_on else 1.0,
                "baro_trust": self.resilience_mgr.sensor_trust["baro"] if self.defense_on else 1.0,
                "vision_trust": self.resilience_mgr.sensor_trust["vision"] if self.defense_on else 1.0,
                "lidar_trust": self.resilience_mgr.sensor_trust["lidar"] if self.defense_on else 1.0
            })
